### ISSUE TITLE
Having trouble with DGEclust

### ISSUE THREAD

**Issue by linyuxi** [dvav/dgeclust#3]
In importing dgeclust, I keep getting "No module named 'manager'". Is there something I need to do to fix this?

Thanks!

**Comment by dvav** [comment]
Hi,

Thank you for your interest in DGEclust. Are you using the correct version of python?

**Comment by linyuxi** [comment]
I'm using Python 3.6.0 and Anaconda 4.3.0. I've recently reinstalled everything again, but am still having the same error message.

**Comment by dvav** [comment]
So, this is where the problem lies. You need python 2.7. Try it and let me
know.

On 9 Feb 2018 18:12, "linyuxi" <notifications@github.com> wrote:

I'm using Python 3.6.0 and Anaconda 4.3.0. I've recently reinstalled
everything again, but am still having the same error message.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/dvav/dgeclust/issues/3#issuecomment-364513094>, or mute
the thread
